# Standards: 0.11
---

# 3.3.2 Ensure /etc/hosts.allow is configured

- name: 3.3.2 - Check if /etc/hosts.allow configuration file exists
  stat:
    path: "/etc/hosts.allow"
  register: hosts_allow_3_3_2
  tags:
    - level-1
    - section-3
    - "3.3.2"
    - scored

- name: 3.3.2 - Ensure IPv6 redirects are not accepted by active kernel parameters
  command: "{{ item }}"
  with_items:
    - "sysctl -w net.ipv6.conf.all.accept_redirects=0"
    - "sysctl -w net.ipv6.conf.default.accept_redirects=0"
    - "sysctl -w net.ipv6.route.flush=1"
  ignore_errors: true
  tags:
    - level-1
    - section-3
    - "3.3.2"
    - scored
